#!/command/with-contenv bash
# shellcheck shell=bash

set -e

. /usr/bin/common.sh

cd /app/sso || exit 1

log_info 'Starting SSO sidecar ...'

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
  s6-setuidgid "$PUID:$PGID" npm install --production
fi

while :
do
  s6-setuidgid "$PUID:$PGID" bash -c "export HOME=$NPMHOME;node --abort_on_uncaught_exception server.js"
  sleep 1
done
